version: '3.7'

services:
  cf-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cf-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"

  cf-kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: cf-kafka-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://cf-kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "cf-zookeeper:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - cf-zookeeper

  jupyter:
    image: quay.io/jupyter/pyspark-notebook
    container_name: jupyter
    user: root
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      CHOWN_HOME: yes 
      CHOWN_HOME_OPTS: '-R'
    volumes:
      - /Users/jerome.lieow/Documents/Jupyter:/home/jovyan
  
  db:
    image: postgres:17.6
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_PASSWORD: sqlpad

  sqlpad:
    image: sqlpad/sqlpad:5
    hostname: 'sqlpad'
    container_name: sqlpad
    ports:
      - '3000:3000'
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
      SQLPAD_CONNECTIONS__pgdemo__name: Postgres
      SQLPAD_CONNECTIONS__pgdemo__driver: postgres
      SQLPAD_CONNECTIONS__pgdemo__host: postgres-db
      SQLPAD_CONNECTIONS__pgdemo__database: sqlpad
      SQLPAD_CONNECTIONS__pgdemo__username: sqlpad
      SQLPAD_CONNECTIONS__pgdemo__password: sqlpad
      SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds: 86400
    volumes:
      - ./seed-data:/etc/sqlpad/seed-data
    
    